name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 3.1.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Setup .NET Core 5.0.100-rc.2.20479.15
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-rc.2.20479.15
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.2
    - name: Build
      run: dotnet run --project ".\build\build.csproj" "build"
      env:
        DEVEXPRESS_NUGET_FEED: ${{secrets.DEVEXPRESS_NUGET_FEED}}
    - name: Publish
      run: dotnet run --project ".\build\build.csproj" "publish" -s
      env:
        DEVEXPRESS_NUGET_FEED: ${{secrets.DEVEXPRESS_NUGET_FEED}}
    - name: Deploy
      run: dotnet run --project ".\build\build.csproj" "deploy" -s
      env:
        WEBDEPLOY_IP: ${{secrets.WEBDEPLOY_IP}}
        WEBDEPLOY_USER: ${{secrets.WEBDEPLOY_USER}}
        WEBDEPLOY_PASS: ${{secrets.WEBDEPLOY_PASS}}
